name: Super Linter (Backend Test)

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'backend-only, sprint-review, release-validation'
  push:
    branches: null

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Backend Test - Verificación básica
        continue-on-error: true
        run: |
          cd MtdrSpring/backend
          chmod +x mvnw
          ./mvnw test -Dtest=ProyectoControllerTest -DfailIfNoTests=false
      
      - name: Path
        continue-on-error: true
        run: |
          sudo mkdir -p /action/lib/.automation/
          sudo chown -R runner:docker /action
          cp java_checks.xml /action/lib/.automation/
      
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          JAVA_FILE_NAME: google_checks.xml
          FILTER_REGEX_INCLUDE: .*MtdrSpring/backend/src/main/.*\.java
